plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.tprondagrupo2'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.tprondagrupo2"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    // Navigation Component
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

    // ViewPager2 para la galeria de fotos
    implementation libs.viewpager2

    // Retrofit + Gson
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson

    // OkHttp + Logging
    implementation libs.okhttp
    implementation libs.okhttp.logging.interceptor

    // Glide para imagenes
    implementation libs.glide

    // SwipeRefreshLayout
    implementation libs.swiperefreshlayout
}